from typing import Protocol
from uuid import UUID


class AuthRepository(Protocol):
    def get_admin_by_username(self, username: str) -> dict | None: ...

    def get_person_by_email(self, email: str) -> dict | None: ...

    def get_admin_by_id(self, admin_id: UUID) -> dict | None: ...

    def get_person_by_id(self, person_id: UUID) -> dict | None: ...

    def get_person_password_hash_by_id(self, person_id: UUID) -> str | None: ...

    def update_person_password(self, person_id: UUID, password_hash: str) -> None: ...
